site_name: Alessandro Rapiti
site_author: Alessandro Rapiti
copyright: ©1986
theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  custom_dir: wwwroot/
extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js
nav:
  - Overview: index.md
  - Libraries: 
    - Rystem: rystem.md
    - Repository: repository.md

